### ISSUE TITLE
More distant foreign object

### ISSUE THREAD

**Issue by garncarz** [gregmuellegger/django-superform#8]
If I want to use `ForeignKeyFormField(MyForm, field_name='close_foreign.distant_foreign')`, it unfortunately doesn't work. Probably because `getattr(MyModel, 'close_foreign.distant_foreign')` neither `getattr(MyModel, 'close_foreign__distant_foreign')` doesn't work that way in Django.

**Comment by dan-passaro** [comment]
Do you have a form for `close_foreign`? Otherwise how does your outermost form link itself to `distant_foreign` without a `close_foreign` in the middle?

**Comment by garncarz** [comment]
Oh, I don't, I see... I'll have to rethink it, thanks.

**Comment by gregmuellegger** [comment]
Right, I don't see any possibility for this to work in a sane way. Currently it is intended that this does not work.

If you have a good vision about how this could behave in all possible cases then I would be glad if we could speak about it. But for now it seems to complex to be integrated anyhow. We should get the docs and anything else straight first before adding more complex features.
